name: Type Check

on:
    push:
        branches: [main] # mainブランチへのpushのみ
    pull_request:
        branches: [main] # mainブランチへのPRのみ

jobs:
    typecheck:
        runs-on: ubuntu-22.04
        timeout-minutes: 5
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - run: npm ci
            - run: npm run typecheck
